name: deliveryorder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  stacked: ^1.5.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  indonesia: ^1.0.1
  flutter_alert: ^0.4.0
  date_format: ^1.0.8
  google_sign_in: ^4.4.6
  data_connection_checker: ^0.3.4
  flutter_cupertino_date_picker: ^1.0.24
  form_field_validator: ^1.0.1
  equatable: ^0.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_native_splash: ^0.1.9

flutter_launcher_name:
  name: "Delivery Order"

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  image: assets/icon.png
  color: "ffffff"

flutter:
  uses-material-design: true
  assets:
    #assets-generator-begin
    #assets/*
    - assets/icon.png
    #assets-generator-end
